[package]
name = "lox"
version = "0.1.0"
authors = ["gilesv <gilesv@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
